---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 24/07/2019 03:38
---


---PlaySound
---
--- Reference : N/A
---
---@param Library string
---@param Sound string
---@param IsLooped boolean
---@return nil
---@public
function RageUI.PlaySound(Library, Sound, IsLooped)
    local sid = nil

    if RageUI.BlockSoundsCount then
        RageUI.BlockSoundsCount = RageUI.BlockSoundsCount - 1

        if RageUI.BlockSoundsCount == 0 then
            RageUI.BlockSoundsCount = nil
        end

        return
    end

    if not IsLooped then
        PlaySoundFrontend(-1, Sound, Library, true)
    else
        if not sid then
            CreateThread(function()
                sid = GetSoundId()

                PlaySoundFrontend(sid, Sound, Library, true)

                Wait(1)

                StopSound(sid)

                ReleaseSoundId(sid)

                sid = nil
            end)
        end
    end
end